# Wikipedia Data Scraping

In [1]:
import pandas as pd

## Ariana Grande

### Honeymoon Tour

In [9]:
# GitHub CSV file link
github_url1 = 'http://raw.githubusercontent.com/liora-symone/cfg3datasets/main/ariana/Honeymoon_clean_v3.csv'

# Read CSV file into a DataFrame
honeymoon_merge = pd.read_csv(github_url1)

# Display the DataFrame
honeymoon_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,The Honeymoon Tour,2015-02-25,Ariana Grande,Rixton Cashmere Cat,54.53,5594.0,5594.0,305063.0,pop,5594.0,NaN,Independence Events Center,Independence,Missouri,United States
1,NaN,The Honeymoon Tour,2015-02-28,Ariana Grande,Rixton Cashmere Cat,46.57,10411.0,10411.0,484877.0,pop,10411.0,NaN,BMO Harris Bradley Center,Milwaukee,Wisconsin,United States
2,NaN,The Honeymoon Tour,2015-03-01,Ariana Grande,Rixton Cashmere Cat,52.95,11272.0,11272.0,596866.0,pop,11272.0,NaN,Xcel Energy Center,Saint Paul,Minnesota,United States
3,NaN,The Honeymoon Tour,2015-03-03,Ariana Grande,Rixton Cashmere Cat,50.93,12470.0,12470.0,635053.0,pop,12470.0,NaN,Allstate Arena,Rosemont,Illinois,United States
4,NaN,The Honeymoon Tour,2015-03-05,Ariana Grande,Rixton Cashmere Cat,52.36,11553.0,11553.0,604962.0,pop,11553.0,NaN,Quicken Loans Arena,Cleveland,Ohio,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Drop rows in the DataFrame where all values are null
honeymoon_merge = honeymoon_merge.dropna(axis=0, how='all')

# Display the DataFrame
honeymoon_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,The Honeymoon Tour,2015-02-25,Ariana Grande,Rixton Cashmere Cat,54.53,5594.0,5594.0,305063.00,pop,5594.0,NaN,Independence Events Center,Independence,Missouri,United States
1,NaN,The Honeymoon Tour,2015-02-28,Ariana Grande,Rixton Cashmere Cat,46.57,10411.0,10411.0,484877.00,pop,10411.0,NaN,BMO Harris Bradley Center,Milwaukee,Wisconsin,United States
2,NaN,The Honeymoon Tour,2015-03-01,Ariana Grande,Rixton Cashmere Cat,52.95,11272.0,11272.0,596866.00,pop,11272.0,NaN,Xcel Energy Center,Saint Paul,Minnesota,United States
3,NaN,The Honeymoon Tour,2015-03-03,Ariana Grande,Rixton Cashmere Cat,50.93,12470.0,12470.0,635053.00,pop,12470.0,NaN,Allstate Arena,Rosemont,Illinois,United States
4,NaN,The Honeymoon Tour,2015-03-05,Ariana Grande,Rixton Cashmere Cat,52.36,11553.0,11553.0,604962.00,pop,11553.0,NaN,Quicken Loans Arena,Cleveland,Ohio,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,NaN,The Honeymoon Tour,2015-10-15,Ariana Grande,Prince Royce,48.79,3766.0,11000.0,68444.97,pop,11000.0,NaN,El Paso County Coliseum,El Paso,Texas,United States
84,NaN,The Honeymoon Tour,2015-10-18,Ariana Grande,DJ Dubz,69.98,15349.0,15349.0,1074116.00,pop,15349.0,NaN,Palacio de los Deportes,Mexico City,Mexico City,Mexico
85,NaN,The Honeymoon Tour,2015-10-21,Ariana Grande,NaN,48.79,3766.0,14000.0,68444.97,pop,14000.0,NaN,Movistar Arena,Santiago,Santiago Metropolitan Region,Chile
86,NaN,The Honeymoon Tour,2015-10-23,Ariana Grande,Olivia Viggiano,48.79,3766.0,50000.0,68444.97,pop,50000.0,NaN,Complejo al RÃ­o,Buenos Aires,Buenos Aires,Argentina
87,NaN,The Honeymoon Tour,2015-10-25,Ariana Grande,NaN,77.88,23560.0,23560.0,1834765.00,pop,23560.0,NaN,Allianz Parque,SÃ£o Paulo,SÃ£o Paulo,Brazil

### Dangerous Woman Tour

In [12]:
# GitHub CSV file link
github_url2 = 'http://raw.githubusercontent.com/liora-symone/cfg3datasets/main/ariana/dangerous_data_cleaned_v2.csv'

# Read CSV file into a DataFrame
dangerous_merge = pd.read_csv(github_url2)

# Display the DataFrame
dangerous_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,Dangerous Tour,2017-02-03,Ariana Grande,Victoria MonÃ©t Little Mix,64.161198,11489,12739,"$737,148",pop,12739,NaN,Talking Stick Resort Arena,Phoenix,Arizona,United States
1,NaN,Dangerous Tour,2017-02-04,Ariana Grande,Victoria MonÃ©t Little Mix,89.570308,9437,10787,"$845,275",pop,10787,NaN,MGM Grand Garden Arena,Las Vegas,Nevada,United States
2,NaN,Dangerous Tour,2017-02-07,Ariana Grande,Victoria MonÃ©t Little Mix,43.889578,9672,13444,"$424,500",pop,13444,NaN,CenturyLink Center Omaha,Omaha,Nebraska,United States
3,NaN,Dangerous Tour,2017-02-09,Ariana Grande,Victoria MonÃ©t Little Mix,52.408008,7343,7995,"$384,832",pop,7995,NaN,BOK Center,Tulsa,Oklahoma,United States
4,NaN,Dangerous Tour,2017-02-14,Ariana Grande,Victoria MonÃ©t Little Mix,53.569038,11472,11472,"$614,544",pop,11472,NaN,Bridgestone Arena,Nashville,Tennessee,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,Dangerous Tour,2017-09-08,Ariana Grande,NaN,98.505301,16505,16580,"$1,625,830",pop,16580,NaN,ICC Sydney Theatre,Sydney,New South Wales,Australia
71,NaN,Dangerous Tour,2017-09-09,Ariana Grande,NaN,98.505301,16505,16580,"$1,625,830",pop,16580,NaN,ICC Sydney Theatre,Sydney,New South Wales,Australia
72,NaN,Dangerous Tour,2017-09-12,Ariana Grande,NaN,97.951716,10604,10604,"$1,038,680",pop,10604,NaN,Brisbane Entertainment Centre,Brisbane,Queensland,Australia
73,NaN,Dangerous Tour,2017-09-19,Ariana Grande,NaN,118.870354,11570,12673,"$1,375,330",pop,12673,NaN,Taipei Arena,Taipei,Taipei,Taiwan
74,NaN,Dangerous Tour,2017-09-21,Ariana Grande,NaN,130.027132,7740,8796,"$1,006,410",pop,8796,NaN,AsiaWorldâ€“Arena,Hong Kong,Hong Kong,Hong Kong

### Sweetener Tour

In [17]:
# GitHub CSV file link
github_url3 = 'http://raw.githubusercontent.com/liora-symone/cfg3datasets/main/ariana/cleaned_sweetener_data_v2.csv'

# Read CSV file into a DataFrame
sweetener_merge = pd.read_csv(github_url3)

# Display the DataFrame
sweetener_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,Sweetener Tour,2019-03-18,Ariana Grande,"Normani, Social House",110.920661,11432,11432,1268045,pop,11432,NaN,Times Union Center,Albany,New York,United States
1,NaN,Sweetener Tour,2019-03-20,Ariana Grande,"Normani, Social House",127.241524,13125,13125,1670045,pop,13125,NaN,TD Garden,Boston,Massachusetts,United States
2,NaN,Sweetener Tour,2019-03-22,Ariana Grande,"Normani, Social House",101.710353,14459,14459,1470630,pop,14459,NaN,KeyBank Center,Buffalo,New York,United States
3,NaN,Sweetener Tour,2019-03-25,Ariana Grande,"Normani, Social House",134.782762,13598,13598,1832776,pop,13598,NaN,Capital One Arena,"Washington, D.C.",District of Columbia,United States
4,NaN,Sweetener Tour,2019-03-26,Ariana Grande,"Normani, Social House",121.719280,14787,14787,1799863,pop,14787,NaN,Wells Fargo Center,Philadelphia,Pennsylvania,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,NaN,Sweetener Tour,2019-12-15,Ariana Grande,Social House,116.694131,10377,10377,1210935,pop,10377,NaN,MGM Grand Garden Arena,Las Vegas,Nevada,United States
93,NaN,Sweetener Tour,2019-12-17,Ariana Grande,Social House,133.343062,22990,22990,3065557,pop,22990,NaN,Chase Center,San Francisco,California,United States
94,NaN,Sweetener Tour,2019-12-18,Ariana Grande,Social House,133.343062,22990,22990,3065557,pop,22990,NaN,Chase Center,San Francisco,California,United States
95,NaN,Sweetener Tour,2019-12-21,Ariana Grande,Social House,131.087873,25810,25810,3383378,pop,25810,NaN,The Forum,Inglewood,California,United States
96,NaN,Sweetener Tour,2019-12-22,Ariana Grande,Social House,131.087873,25810,25810,3383378,pop,25810,NaN,The Forum,Inglewood,California,United States

In [18]:
# Concatenate DataFrames vertically
ariana_merge = pd.concat([honeymoon_merge, dangerous_merge, sweetener_merge], ignore_index=True)

# Display the concatenated DataFrame
ariana_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,The Honeymoon Tour,2015-02-25,Ariana Grande,Rixton Cashmere Cat,54.530000,5594.0,5594.0,305063.0,pop,5594.0,NaN,Independence Events Center,Independence,Missouri,United States
1,NaN,The Honeymoon Tour,2015-02-28,Ariana Grande,Rixton Cashmere Cat,46.570000,10411.0,10411.0,484877.0,pop,10411.0,NaN,BMO Harris Bradley Center,Milwaukee,Wisconsin,United States
2,NaN,The Honeymoon Tour,2015-03-01,Ariana Grande,Rixton Cashmere Cat,52.950000,11272.0,11272.0,596866.0,pop,11272.0,NaN,Xcel Energy Center,Saint Paul,Minnesota,United States
3,NaN,The Honeymoon Tour,2015-03-03,Ariana Grande,Rixton Cashmere Cat,50.930000,12470.0,12470.0,635053.0,pop,12470.0,NaN,Allstate Arena,Rosemont,Illinois,United States
4,NaN,The Honeymoon Tour,2015-03-05,Ariana Grande,Rixton Cashmere Cat,52.360000,11553.0,11553.0,604962.0,pop,11553.0,NaN,Quicken Loans Arena,Cleveland,Ohio,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,NaN,Sweetener Tour,2019-12-15,Ariana Grande,Social House,116.694131,10377.0,10377.0,1210935,pop,10377.0,NaN,MGM Grand Garden Arena,Las Vegas,Nevada,United States
256,NaN,Sweetener Tour,2019-12-17,Ariana Grande,Social House,133.343062,22990.0,22990.0,3065557,pop,22990.0,NaN,Chase Center,San Francisco,California,United States
257,NaN,Sweetener Tour,2019-12-18,Ariana Grande,Social House,133.343062,22990.0,22990.0,3065557,pop,22990.0,NaN,Chase Center,San Francisco,California,United States
258,NaN,Sweetener Tour,2019-12-21,Ariana Grande,Social House,131.087873,25810.0,25810.0,3383378,pop,25810.0,NaN,The Forum,Inglewood,California,United States
259,NaN,Sweetener Tour,2019-12-22,Ariana Grande,Social House,131.087873,25810.0,25810.0,3383378,pop,25810.0,NaN,The Forum,Inglewood,California,United States

### Merge Ariana & Coldplay data

In [20]:
# GitHub CSV file link
github_url4 = 'https://raw.githubusercontent.com/liora-symone/cfg3datasets/main/coldplay/coldplay_merged_data_v1.csv'

# Read CSV file into a DataFrame
coldplay_merge = pd.read_csv(github_url4)

# Display the DataFrame
coldplay_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,A Head Full of Dreams Tour,2016-03-31,Coldplay,Lianne La Havas Hana,68.197777,97069.0,97069,6619890.00,"permanent wave, pop",97069,NaN,Estadio Ciudad de La Plata,La Plata,Buenos Aires Province,Argentina
1,NaN,A Head Full of Dreams Tour,2016-04-01,Coldplay,Lianne La Havas Hana,68.197777,97069.0,97069,6619890.00,"permanent wave, pop",97069,NaN,Estadio Ciudad de La Plata,La Plata,Buenos Aires Province,Argentina
2,NaN,A Head Full of Dreams Tour,2016-04-03,Coldplay,Lianne La Havas MarÃ­a Colores,74.676822,60787.0,60787,4539380.00,"permanent wave, pop",60787,NaN,Estadio Nacional de Chile,Santiago,Santiago Metropolitan Region,Chile
3,NaN,A Head Full of Dreams Tour,2016-04-05,Coldplay,Lianne La Havas Gala Brie,110.448536,43720.0,43720,4828810.00,"permanent wave, pop",43720,NaN,Estadio Nacional del PerÃº,Lima,Lima,Peru
4,NaN,A Head Full of Dreams Tour,2016-04-07,Coldplay,Lianne La Havas TiÃª,87.908425,46563.0,46563,4093280.00,"permanent wave, pop",46563,NaN,Allianz Parque,SÃ£o Paulo,SÃ£o Paulo,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,NaN,Ghost Stories Tour,2014-06-12,Coldplay,NaN,104.780000,207.0,1568,324815.29,"permanent wave, pop",3100,NaN,Tokyo Dome City Hall,Tokyo,Tokyo,Japan
190,NaN,Ghost Stories Tour,2014-06-19,Coldplay,Kylie Minogue,203.010000,207.0,1568,324815.29,"permanent wave, pop",1600,NaN,Enmore Theatre,Sydney,New South Wales,Australia
191,NaN,Ghost Stories Tour,2014-07-01,Coldplay,Aluna George,61.610000,207.0,1568,324815.29,"permanent wave, pop",5272,NaN,Royal Albert Hall,London,England,England
192,NaN,Ghost Stories Tour,2014-07-02,Coldplay,NaN,61.610000,207.0,1568,324815.29,"permanent wave, pop",5272,NaN,Royal Albert Hall,London,England,England
193,NaN,Ghost Stories Tour,2014-12-06,Coldplay,NaN,105.800000,1511.0,1511,159859.00,"permanent wave, pop",1511,NaN,BMW Welt,Munich,Bavaria,Germany

In [27]:
# GitHub CSV file link
github_url5 = 'http://raw.githubusercontent.com/liora-symone/cfg3datasets/main/ed_sheeran/edsheeran_merged_data_v1.csv'

# Read CSV file into a DataFrame
edsheeran_merge = pd.read_csv(github_url5)

# Display the DataFrame
edsheeran_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,Divide Tour,2017-03-16,Ed Sheeran,Anne-Marie Ryan McMullan,52.437221,23256,23256,"$1,219,480","pop, singer-songwriter pop, uk pop",23256,NaN,Pala Alpitour,Turin,Piedmont,Italy
1,NaN,Divide Tour,2017-03-17,Ed Sheeran,Anne-Marie Ryan McMullan,52.437221,23256,23256,"$1,219,480","pop, singer-songwriter pop, uk pop",23256,NaN,Pala Alpitour,Turin,Piedmont,Italy
2,NaN,Divide Tour,2017-03-19,Ed Sheeran,Anne-Marie Ryan McMullan,79.519870,14444,14444,"$1,148,585","pop, singer-songwriter pop, uk pop",14444,NaN,Hallenstadion,ZÃ¼rich,ZÃ¼rich,Switzerland
3,NaN,Divide Tour,2017-03-20,Ed Sheeran,Anne-Marie Ryan McMullan,76.164955,12076,12108,"$919,768","pop, singer-songwriter pop, uk pop",12108,NaN,Olympiahalle,Munich,Bavaria,Germany
4,NaN,Divide Tour,2017-03-22,Ed Sheeran,Anne-Marie Ryan McMullan,68.307848,10843,10848,"$740,662","pop, singer-songwriter pop, uk pop",10848,NaN,SAP Arena,Mannheim,Baden-WÃ¼rttemberg,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,Plus Tour,2015-12-02,Ed Sheeran,NaN,67.764835,31816,31816,2156006,"pop, singer-songwriter pop, uk pop",31816,NaN,HBF Park,Perth,Western Australia,Australia
463,NaN,Plus Tour,2015-12-05,Ed Sheeran,NaN,65.437367,67353,67353,4407403,"pop, singer-songwriter pop, uk pop",67353,NaN,AAMI Park,Melbourne,Victoria,Australia
464,NaN,Plus Tour,2015-12-06,Ed Sheeran,NaN,65.437367,67353,67353,4407403,"pop, singer-songwriter pop, uk pop",67353,NaN,AAMI Park,Melbourne,Victoria,Australia
465,NaN,Plus Tour,2015-12-09,Ed Sheeran,NaN,62.594956,47617,47617,2980584,"pop, singer-songwriter pop, uk pop",47617,NaN,Allianz Stadium,Sydney,New South Wales,Australia
466,NaN,Plus Tour,2015-12-12,Ed Sheeran,NaN,58.736048,43201,43201,2537456,"pop, singer-songwriter pop, uk pop",43201,NaN,Mount Smart Stadium,Auckland,Auckland,New Zealand

In [28]:
# Concatenate DataFrames vertically
ariana_coldplay_ed = pd.concat([ariana_merge, coldplay_merge, edsheeran_merge], ignore_index=True)

# Display the concatenated DataFrame
ariana_coldplay_ed

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,The Honeymoon Tour,2015-02-25,Ariana Grande,Rixton Cashmere Cat,54.530000,5594.0,5594.0,305063.0,pop,5594.0,NaN,Independence Events Center,Independence,Missouri,United States
1,NaN,The Honeymoon Tour,2015-02-28,Ariana Grande,Rixton Cashmere Cat,46.570000,10411.0,10411.0,484877.0,pop,10411.0,NaN,BMO Harris Bradley Center,Milwaukee,Wisconsin,United States
2,NaN,The Honeymoon Tour,2015-03-01,Ariana Grande,Rixton Cashmere Cat,52.950000,11272.0,11272.0,596866.0,pop,11272.0,NaN,Xcel Energy Center,Saint Paul,Minnesota,United States
3,NaN,The Honeymoon Tour,2015-03-03,Ariana Grande,Rixton Cashmere Cat,50.930000,12470.0,12470.0,635053.0,pop,12470.0,NaN,Allstate Arena,Rosemont,Illinois,United States
4,NaN,The Honeymoon Tour,2015-03-05,Ariana Grande,Rixton Cashmere Cat,52.360000,11553.0,11553.0,604962.0,pop,11553.0,NaN,Quicken Loans Arena,Cleveland,Ohio,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
916,NaN,Plus Tour,2015-12-02,Ed Sheeran,NaN,67.764835,31816.0,31816.0,2156006,"pop, singer-songwriter pop, uk pop",31816.0,NaN,HBF Park,Perth,Western Australia,Australia
917,NaN,Plus Tour,2015-12-05,Ed Sheeran,NaN,65.437367,67353.0,67353.0,4407403,"pop, singer-songwriter pop, uk pop",67353.0,NaN,AAMI Park,Melbourne,Victoria,Australia
918,NaN,Plus Tour,2015-12-06,Ed Sheeran,NaN,65.437367,67353.0,67353.0,4407403,"pop, singer-songwriter pop, uk pop",67353.0,NaN,AAMI Park,Melbourne,Victoria,Australia
919,NaN,Plus Tour,2015-12-09,Ed Sheeran,NaN,62.594956,47617.0,47617.0,2980584,"pop, singer-songwriter pop, uk pop",47617.0,NaN,Allianz Stadium,Sydney,New South Wales,Australia
920,NaN,Plus Tour,2015-12-12,Ed Sheeran,NaN,58.736048,43201.0,43201.0,2537456,"pop, singer-songwriter pop, uk pop",43201.0,NaN,Mount Smart Stadium,Auckland,Auckland,New Zealand

In [32]:
# GitHub CSV file link
github_url6 = 'http://raw.githubusercontent.com/liora-symone/cfg3datasets/main/justin/justin_merged_data_v2.csv'

# Read CSV file into a DataFrame
justin_merge = pd.read_csv(github_url6)

# Display the DataFrame
justin_merge

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,Believe Tour,2012-09-29,Justin Bieber,"Cody Simpson, Carly Rae Jepsen",75.473637,13428.0,13428.0,1013460.0,"canadian pop, pop",13428,NaN,Jobingcom Arena,Glendale,Arizona,United States
1,NaN,Believe Tour,2012-09-30,Justin Bieber,"Cody Simpson, Carly Rae Jepsen",79.744372,13504.0,13504.0,1076868.0,"canadian pop, pop",13504,NaN,MGM Grand Garden Arena,Las Vegas,Nevada,United States
2,NaN,Believe Tour,2012-02-10,Justin Bieber,"Cody Simpson, Carly Rae Jepsen",81.279932,27546.0,27546.0,2238937.0,"canadian pop, pop",27546,NaN,Staples Center,Los Angeles,California,United States
3,NaN,Believe Tour,2012-03-10,Justin Bieber,"Cody Simpson, Carly Rae Jepsen",81.279932,27546.0,27546.0,2238937.0,"canadian pop, pop",27546,NaN,Staples Center,Los Angeles,California,United States
4,NaN,Believe Tour,2012-05-10,Justin Bieber,"Cody Simpson, Carly Rae Jepsen",110.625324,11965.0,11965.0,1323632.0,"canadian pop, pop",11965,NaN,Save Mart Center,Fresno,California,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,NaN,Purpose Tour,2017-06-18,Justin Bieber,Halsey,113.780804,30653.0,31740.0,3487723.0,"canadian pop, pop","31,740",NaN,RDS Arena,Dublin,Leinster,Ireland
339,NaN,Purpose Tour,2017-06-24,Justin Bieber,NaN,NaN,NaN,NaN,NaN,"canadian pop, pop",50000,NaN,Stade Pierre-Mauroy,Lille,Hauts-de-France,France
340,NaN,Purpose Tour,2017-06-30,Justin Bieber,NaN,NaN,NaN,NaN,NaN,"canadian pop, pop",38000,NaN,Commerzbank Arena,Frankfurt,Hesse,Germany
341,NaN,Purpose Tour,2017-06-25,Justin Bieber,Halsey,69.736483,38434.0,45021.0,2680252.0,"canadian pop, pop","45,021",NaN,Principality Stadium,Cardiff,Wales,Wales
342,NaN,Purpose Tour,2017-07-02,Justin Bieber,Martin Garrix Tove Lo Anne-Marie,NaN,NaN,NaN,NaN,"canadian pop, pop",65000,NaN,Hyde Park,London,England,England

In [33]:
# Concatenate DataFrames vertically
wikitourdata = pd.concat([ariana_coldplay_ed, justin_merge], ignore_index=True)

# Display the concatenated DataFrame
wikitourdata

,event_id,event_name,date,artist_name,support_act,average_price,tickets_sold,tickets_available,revenue,genre,capacity,venue_id,venue_name,venue_city,venue_state,venue_country
0,NaN,The Honeymoon Tour,2015-02-25,Ariana Grande,Rixton Cashmere Cat,54.530000,5594.0,5594.0,305063.0,pop,5594.0,NaN,Independence Events Center,Independence,Missouri,United States
1,NaN,The Honeymoon Tour,2015-02-28,Ariana Grande,Rixton Cashmere Cat,46.570000,10411.0,10411.0,484877.0,pop,10411.0,NaN,BMO Harris Bradley Center,Milwaukee,Wisconsin,United States
2,NaN,The Honeymoon Tour,2015-03-01,Ariana Grande,Rixton Cashmere Cat,52.950000,11272.0,11272.0,596866.0,pop,11272.0,NaN,Xcel Energy Center,Saint Paul,Minnesota,United States
3,NaN,The Honeymoon Tour,2015-03-03,Ariana Grande,Rixton Cashmere Cat,50.930000,12470.0,12470.0,635053.0,pop,12470.0,NaN,Allstate Arena,Rosemont,Illinois,United States
4,NaN,The Honeymoon Tour,2015-03-05,Ariana Grande,Rixton Cashmere Cat,52.360000,11553.0,11553.0,604962.0,pop,11553.0,NaN,Quicken Loans Arena,Cleveland,Ohio,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,NaN,Purpose Tour,2017-06-18,Justin Bieber,Halsey,113.780804,30653.0,31740.0,3487723.0,"canadian pop, pop","31,740",NaN,RDS Arena,Dublin,Leinster,Ireland
1260,NaN,Purpose Tour,2017-06-24,Justin Bieber,NaN,NaN,NaN,NaN,NaN,"canadian pop, pop",50000,NaN,Stade Pierre-Mauroy,Lille,Hauts-de-France,France
1261,NaN,Purpose Tour,2017-06-30,Justin Bieber,NaN,NaN,NaN,NaN,NaN,"canadian pop, pop",38000,NaN,Commerzbank Arena,Frankfurt,Hesse,Germany
1262,NaN,Purpose Tour,2017-06-25,Justin Bieber,Halsey,69.736483,38434.0,45021.0,2680252.0,"canadian pop, pop","45,021",NaN,Principality Stadium,Cardiff,Wales,Wales
1263,NaN,Purpose Tour,2017-07-02,Justin Bieber,Martin Garrix Tove Lo Anne-Marie,NaN,NaN,NaN,NaN,"canadian pop, pop",65000,NaN,Hyde Park,London,England,England

In [34]:
# FInd the unique values to check that all artists have been merged
unique_values = wikitourdata['artist_name'].unique()

# Display the unique values
print(unique_values)

['Ariana Grande' 'Coldplay' 'Ed Sheeran' 'Justin Bieber']

In [35]:
# Save the DataFrame to a CSV file
wikitourdata.to_csv('wikitourdata.csv', index=False)